### DISCUSSION TITLE
how to configure the grpc service URL in the jaeger custom resource

### DISCUSSION THREAD

**Discussion by ErikEngerd** [robbert229/jaeger-postgresql#94] [Q&A]
The documentation refers to the jaeger documentation as the ultimate resource but that documentation is focused exclusively on configuring a sidecar container and there is no concrete example on how to configure this: 

I now have this: 

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-main
  namespace: observability
spec:
  strategy: allInOne
  allInOne:
    options:
      log-level: info
  ingress:
    enabled: false # ingress for jaeger-query
  storage:
#    type: badger
#    options:
#      badger:
#        ephemeral: false
#        span-store-ttl: 24h
#        directory-key: "/badger/key"
#        directory-value: "/badger/data"
    type: grpc-plugin
    options:
      grpc:
        service: jaeger-database-jaeger-postgresql:12345
    .....more config...
```

But this leads to an error message in the jaeger operator: 

```
2025-04-25T13:31:30Z    ERROR   Reconciler error        {"controller": "jaeger", "controllerGroup": "jaegertracing.io", "controllerKind": "Jaeger", "Jaeger": {"name":"jaeger-main","namespace":"observability"}, "namespace": "observability", "name": "jaeger-main", "reconcileID": "a9b49a2e-f113-4be0-ad9c-514ef28b8ec5", "error": "Deployment.apps \"jaeger-main\" is invalid: spec.template.spec.initContainers[0].image: Required value"}
```
